name = "SnoopCompileCore"
uuid = "e2b509da-e806-4183-be48-004708413034"
author = ["Tim Holy <tim.holy@gmail.com>"]
version = "2.1.1"

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
julia = "1"
