name = "Blackjack"
uuid = "a00d2ebe-aa49-43d7-8128-e35d2ba76b09"
version = "0.1.0"
authors = ["runner "]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.3"
