name = "Blackjack"
uuid = "0613c755-6f96-492b-8f1d-2121b461db20"
version = "0.1.0"
authors = ["runner "]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.4"
