name = "Blackjack"
uuid = "fa056ff2-47ae-4889-adda-e2f85cd93503"
version = "0.1.0"
authors = ["runner "]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.4"
