name = "Blackjack"
uuid = "f7952194-1e4e-4c54-8cda-7fefb239fb83"
authors = ["runner "]
version = "0.1.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.2.1"
