name = "Blackjack"
uuid = "ed5adf85-ff85-46b2-b0e4-6dcbb9b73627"
authors = ["runner "]
version = "0.1.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.2.1"
