name = "Blackjack"
uuid = "6b7a09cf-e800-4634-8d85-da8a3a6e9d8d"
version = "0.1.0"
authors = ["runner "]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.3.3"
