name = "Blackjack"
uuid = "277ebdf7-2063-437d-b4a8-371e674077b3"
authors = ["runner "]
version = "0.1.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.2.1"
