name = "BlackjackFacecards"
uuid = "beb14567-3e7d-4489-bf9c-4a1366e0245e"
version = "0.1.0"
authors = ["runner "]

[deps]
Blackjack = "543165b4-cfc3-4d1a-836d-c66317f58253"

[sources]
Blackjack = {path = "/home/runner/work/SnoopCompile.jl/SnoopCompile.jl/docs/build/tutorials/Blackjack"}
