name = "BlackjackFacecards"
uuid = "775ca54e-85ad-4db0-8335-bc37df084946"
version = "0.1.0"
authors = ["runner "]

[deps]
Blackjack = "40809569-acdc-4d91-8a35-d64f97f79760"

[sources]
Blackjack = {path = "/home/runner/work/SnoopCompile.jl/SnoopCompile.jl/docs/build/tutorials/Blackjack"}
