name = "BlackjackFacecards"
uuid = "82e025b3-1886-498f-ac8a-df6e39bcb5e2"
version = "0.1.0"
authors = ["runner "]

[deps]
Blackjack = "d9af2ba9-6f0d-4337-abce-ba03f6d41b5b"

[sources]
Blackjack = {path = "/home/runner/work/SnoopCompile.jl/SnoopCompile.jl/docs/build/tutorials/Blackjack"}
