name = "Blackjack"
uuid = "02e2f192-e8b9-427e-a16d-ffa1b2c1baf0"
authors = ["runner "]
version = "0.1.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.2.1"
